apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: tra-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
        - name: backstage
          image: ghcr.io/dfe-digital/tra-backstage-poc:000645ee10c4eb804653038950ceee842c64b28e
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: backstage-secrets
---
# kubernetes/backstage-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: tra-development
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http